version: '3.5'

services:
    consul:
        container_name: consul
        image: consul:latest
        networks:
            - kountnet
        ports:
            - "8500:8500"
            - "8300:8300"
        volumes:
            - ./config:/config
            - ../vault-helper/system/etc:/config/vault-helper
            - ./_data/consul:/data
        # https://github.com/hashicorp/consul/issues/1580 -- raft-protocol 3 is required!
        command: agent -raft-protocol 3 -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -datacenter internal -ui

    vault:
        container_name: vault
        image: vault:latest
        networks:
            - kountnet
        depends_on:
            - consul
        ports:
            - "8200:8200"
        volumes:
            - ./config:/config
            - ../vault-helper/system/etc:/config/vault-helper
            - ./_data/consul:/data
        cap_add:
            - IPC_LOCK
        command: server -config=/config/vault.hcl

    backup:
        container_name: backup
        build: backup/
        networks:
            - kountnet
        depends_on:
            - consul
        volumes:
            - ./_data/backup:/backup/
        command: consul-backup

networks:
    kountnet:
        name: kountnet
