version: '3.5'

services:
    consul:
        container_name: consul
        image: consul
        networks:
            - kountnet
        ports:
            - "8500:8500"
            - "8300:8300"
        volumes:
            - ./config:/config
            - ../vault-helper/system/etc:/config/vault-helper
            - consul:/data
        # https://github.com/hashicorp/consul/issues/1580 -- raft-protocol 3 is required!
        command: agent -raft-protocol 3 -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -datacenter internal -ui

    vault:
        container_name: vault
        image: vault
        networks:
            - kountnet
        links:
            - consul
        depends_on:
            - consul
        ports:
            - "8200:8200"
        volumes:
            - ./config:/config
            - ../vault-helper/system/etc:/config/vault-helper
            - consul:/data
        cap_add:
            - IPC_LOCK
        command: server -config=/config/vault.hcl

    webui:
        container_name: webui
        image: djenriquez/vault-ui
        networks:
            - kountnet
        ports:
            - "8000:8000"
        links:
            - vault
        environment:
            NODE_TLS_REJECT_UNAUTHORIZED: 0
            VAULT_URL_DEFAULT: http://vault:8200

    backup:
        container_name: backup
        build: backup/
        networks:
            - kountnet
        links:
            - consul
        volumes:
            - ./_data/backup:/backup/
        command: consul-backup

volumes:
    consul:

networks:
    kountnet:
        name: kountnet
